version: '3.4'

services:
  cadb:
    container_name: cadb
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1422:1433"


  caapi:
    container_name: caapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SDAConnectionString=Data Source=cadb;Initial Catalog=Fuzzy;User ID=sa;Password=P@ssw0rd;"
      - "ConnectionStrings:IdentityConnectionString=Data Source=cadb;Initial Catalog=caIdentity;User ID=sa;Password=P@ssw0rd;"
    depends_on:
      - cadb
    ports:
      - "7244:80"
      - "8005:443"



